# -*- coding: utf-8 -*-
"""bootcamp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KZToKcplYMbA4rFJ3HIoCPSC1Wuw4Xlp
"""

#Sipariş zamanını görebilmek ve kayıt tutmak için öncelikle gerekli kitaplıkları import ediyoruz.
import datetime
import csv

#Menüyü barındırması için bir dosya oluşturuyor ve menümüzü buraya yazıyoruz.
menu_file = open('menu.txt', "w")
menu_file.write('KLASİK PİZZALARIMIZ \n1.Margherita Pizza \n2.Funghi Pizza\n3.Piccante Pizza\n4.Pepperoni Pizza\n5.Karışık Pizza\n6.Veggie Pizza\nMALZEMELERİMİZ\n'+
    '11.Mozzarella Peyniri\n12.Sucuk\n13.Salam\n14.Sosis\n15.Yeşil Biber\n16.Mantar\n17.Mısır\n18.Siyah Zeytin\n19.Domates\n20.Soğan\n21.Kekik'+
    '\n22.Jalepeno Biberi')
menu_file.close()

#Şimdi menüyü ekrana bastırıyoruz.
menu_file = open('menu.txt', "r", encoding="utf-8")
for line in menu_file:
  print(line)
menu_file.close()

#Pizza üst sınıfını ve alt sınıflarımmızı oluşturuyoruz.
class pizza:
  def __init__(self, description, cost):
    self.description = description
    self.cost = int(cost)
  def get_description(self):
    return self.description
  def get_cost(self):
    return self.cost
  def print_pizza(self):
        print(self.get_description())
        print("Pizzanın Değeri: " + str(self.get_cost()))

margherita = pizza("Margherita Pizza İçeriği: Domates Sosu, Mozzarella Peyniri", 85)
funghi = pizza("Funghi Pizza İçeriği: Domates Sosu, Mozzarella Peyniri,Mantar, Kekik", 90)
piccante = pizza("Piccante Pizzaİçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk, Jalepeno Biberi, Mantar", 105)
pepperoni = pizza("Pepperoni Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk", 100)
karisik = pizza("Karışık Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk, Sosis, Salam, Mantar, Mısır, Siyah Zeytin, Yeşil Biber", 110)
veggie = pizza("Veggie Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Mantar, Domates, Soğan, Siyah Zeytin, Mısır, Yeşil Biber", 95)

#Kullanıcıya siparişini soruyor ve pizza açıklamalarını ve değerlerini yazdırıyoruz.

def pizzasiparis():
  global anafiyat
  while True:
    siparis_no = input("Lütfen seçmek istediğiniz pizzanın numarasını giriniz: ")   
    if siparis_no == '1':
        margherita.print_pizza()
        anafiyat = 85
        return "Margherita Pizza İçeriği: Domates Sosu, Mozzarella Peyniri\nPizzanın Değeri: 85"
        break
    elif siparis_no == '2':
        funghi.print_pizza()
        anafiyat = 90
        return "Funghi Pizza İçeriği: Domates Sosu, Mozzarella Peyniri,Mantar, Kekik\nPizzanın Değeri: 90"
        break
    elif siparis_no == '3':
        piccante.print_pizza()
        anafiyat = 105
        return "Piccante Pizzaİçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk, Jalepeno Biberi, Mantar\nPizzanın Değeri: 105"
        break
    elif siparis_no == '4':
        pepperoni.print_pizza()
        anafiyat = 100
        return "Pepperoni Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk\nPizzanın Değeri: 100"
        break
    elif siparis_no == '5':
        karisik.print_pizza()
        anafiyat = 110
        return "Karışık Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Sucuk, Sosis, Salam, Mantar, Mısır, Siyah Zeytin, Yeşil Biber\nPizzanın Değeri: 110"
        break
    elif siparis_no == '6':
        veggie.print_pizza()
        anafiyat = 95
        return "Veggie Pizza İçeriği: Domates Sosu, Mozzarella Peyniri, Mantar, Domates, Soğan, Siyah Zeytin, Mısır, Yeşil Biber\nPizzanın Değeri: 95"
        break
    else:
        print("Lütfen pizzalara karşılık gelen numaralardan birini seçiniz.")
aciklama = pizzasiparis()

#Decorator sınıfımızı ve alt sınıflarımızı oluşturuyoruz.
class decorator:
    def __init__(self, description, cost):
        super().__init__()
        self.description = description
        self.cost = cost
    def get_description(self):
        return self.description
    def get_cost(self):
        return self.cost
    def print_decorator(self):
        print(self.get_description())
        print("Ek Malzeme Değeri: " + str(self.get_cost()))

mozzarella = decorator("Pizzanıza Ekstra Mozzarella Peyniri Eklenecektir", 6)
sucuk = decorator("Pizzanıza Ekstra Sucuk Eklenecektir", 6)
salam = decorator("Pizzanıza Ekstra Salam Eklenecektir", 6)
sosis = decorator("Pizzanıza Ekstra Sosis Eklenecektir", 6)
yesilbiber = decorator("Pizzanıza Ekstra Yeşil Biber Eklenecektir", 4)
mantar = decorator("Pizzanıza Ekstra Mantar Eklenecektir", 4)
mısır = decorator("Pizzanıza Ekstra Mısır Eklenecektir", 4)
siyahzeytin = decorator("Pizzanıza Ekstra Siyah Zeytin Eklenecektir", 4)
domates = decorator("Pizzanıza Ekstra Domates Eklenecektir", 4)
sogan = decorator("Pizzanıza Ekstra Soğan Eklenecektir", 4)
kekik = decorator("Pizzanıza Ekstra Kekik Eklenecektir", 2)
jalepeno = decorator("Pizzanıza Ekstra Jalepeno Biberi Eklenecektir", 5)

#Eklemek istenen malzeme olup olmadığını soruyoruz.
def malzeme():
  global ekfiyat 
  ekfiyat = 0
  while True:
    siparis_no = input("Lütfen pizzanıza eklemek istediğiniz malzemeyi giriniz. Eğer malzeme eklemek istemiyorsanız 0 tuşuna basınız: ")   
    if siparis_no == '11':
        mozzarella.print_decorator()
        ekfiyat += 6
        return "Pizzanıza Ekstra Mozzarella Peyniri Eklenecektir. Eklenecek Değer: 6"
    elif siparis_no == '12':
        sucuk.print_decorator()
        ekfiyat +=6
        return "Pizzanıza Ekstra Sucuk Eklenecektir. Eklenecek Değer: 6"
    elif siparis_no == '13':
        salam.print_decorator()
        ekfiyat +=6
        return "Pizzanıza Ekstra Salam Eklenecektir. Eklenecek Değer: 6"
    elif siparis_no == '14':
        sosis.print_decorator()
        ekfiyat +=6
        return "Pizzanıza Ekstra Sosis Eklenecektir. Eklenecek Değer: 6"
    elif siparis_no == '15':
        yesilbiber.print_decorator()
        ekfiyat += 4
        return "Pizzanıza Ekstra Yeşil Biber Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '16':
        mantar.print_decorator()
        ekfiyat +=4
        return"Pizzanıza Ekstra Mantar Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '17':
        mısır.print_decorator()
        ekfiyat +=4
        return "Pizzanıza Ekstra Mısır Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '18':
        siyahzeytin.print_decorator()
        ekfiyat += 4
        return "Pizzanıza Ekstra Siyah Zeytin Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '19':
        domates.print_decorator()
        ekfiyat +=4
        return "Pizzanıza Ekstra Domates Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '20':
        sogan.print_decorator()
        ekfiyat +=4
        return "Pizzanıza Ekstra Soğan Eklenecektir. Eklenecek Değer: 4"
    elif siparis_no == '21':
        kekik.print_decorator()
        ekfiyat +=2
        return "Pizzanıza Ekstra Kekik Eklenecektir. Eklenecek Değer: 2"
    elif siparis_no == '22':
        jalepeno.print_decorator()
        ekfiyat +=5
        return "Pizzanıza Ekstra Jalepeno Biberi Eklenecektir. Eklenecek Değer: 5"
    elif siparis_no == '0':
      break
    else:
        print("Lütfen malzemelere karşılık gelen numaralardan birini veya 0'ı seçiniz.")
ek = malzeme()
#Pizza ve ekleri fiyatını hesaplıyoruz.
totalfiyat = anafiyat + ekfiyat

#Şimdi sipariş özetini kullanıcıya söylüyoruz.
ozet = "Sipariş Özeti: "+ aciklama +"\n"+ ek + "\nSiparişinizin toplam fiyatı: "+ str(totalfiyat)
print(ozet)

#Kullanıcı bilgilerini istiyoruz.
isim = input("Ad, Soyad: ")
tc = input("Lütfen T.C. kimlik numaranızı giriniz: ")
kartno = input("Lütfen kredi kartı numaranızı giriniz: ")
kartsifre = input("Lütfen kredi kartı şifrenizi giriniz: ")
sipariszamanı = datetime.datetime.now()

#Bilgileri kaydetmek için önce csv doyası açıyor sonra girilecek verileri giriyoruz.
filename = 'Orders_Database.csv'
with open(filename, 'w', newline='') as csvfile:
   csvwriter = csv.writer(csvfile)
   row = ['Kullanıcı İsmi', 'T.C. Kimlik Numarası','Kredi Kartı Numarası','Sipariş Açıklaması','Sipariş Zamanı', 'Kredi Kartı Şifresi']
   csvwriter.writerow(row)
with open(filename, 'a', newline='') as csvfile:
   csvwriter = csv.writer(csvfile)
   row = [isim, tc, kartno, ozet, sipariszamanı, kartsifre]
   csvwriter.writerow(row)

